"use client";

import { useState } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface GlossaryTerm {
  term: string;
  category: string;
  definition: string;
  range?: string;
  subItems?: { label: string; description: string }[];
  example?: string;
  formula?: string;
}

// ─── Glossary data ────────────────────────────────────────────────────────────

const TERMS: GlossaryTerm[] = [
  {
    term: "Quality Score",
    category: "Core Metrics",
    definition: "How well the AI responded to a user's request. Measures four dimensions: relevance (did it answer the right question?), accuracy (was the information correct?), completeness (did it fully address the request?), and helpfulness (would the user be satisfied?).",
    range: "0–100. Scored by an AI evaluator reading the full conversation.",
    subItems: [
      { label: "80–100", description: "Excellent — AI fully addressed the request" },
      { label: "60–79",  description: "Good — mostly helpful with minor gaps" },
      { label: "40–59",  description: "Needs improvement — partial or unclear responses" },
      { label: "20–39",  description: "Poor — significant problems" },
      { label: "0–19",   description: "Failing — AI could not help" },
    ],
    example: "A quality score of 85 means the AI gave a highly relevant, accurate, and complete answer.",
  },
  {
    term: "Completion Status",
    category: "Core Metrics",
    definition: "Whether the user accomplished their goal by the end of the conversation.",
    subItems: [
      { label: "Completed",  description: "User got what they needed — goal fully resolved" },
      { label: "Partial",    description: "User got some help but not fully resolved — in-progress or mixed outcome" },
      { label: "Failed",     description: "AI couldn't help, gave wrong answer, or user expressed frustration" },
      { label: "Abandoned",  description: "User stopped responding mid-conversation without resolution" },
    ],
    example: "If a user asks how to fix a bug and the AI gives a working solution, status = Completed.",
  },
  {
    term: "Health Score",
    category: "Core Metrics",
    definition: "A single number summarizing overall AI product health. Combines quality, completion, and failure rate into one score.",
    formula: "Health Score = (avg quality / 100) × completion rate × (1 − failure rate) × 100",
    range: "0–100. Higher is better.",
    subItems: [
      { label: "80+",  description: "Excellent — AI is performing well across all dimensions" },
      { label: "60–79", description: "Good — some areas need attention" },
      { label: "40–59", description: "Needs work — significant quality or completion issues" },
      { label: "Below 40", description: "Critical — major problems impacting users" },
    ],
    example: "Health = 0.72 (quality) × 0.65 (completion) × 0.78 (1−failure) = 0.365 → 36.5",
  },
  {
    term: "Impact Score",
    category: "Core Metrics",
    definition: "How urgently a topic needs fixing. Combines conversation volume, failure rate, and quality gap to prioritize improvement work.",
    formula: "Impact Score = volume × failure rate × (100 − avg quality) / 100",
    range: "Higher = fix first.",
    example: "A topic with 10,000 conversations, 60% failure rate, and quality 40/100 has a high impact score — it's hurting many users badly.",
  },
  {
    term: "Topic / Intent",
    category: "Topics",
    definition: "What the user was trying to accomplish, auto-detected by AI reading the conversation. Expressed as a specific label like 'python web scraping' or 'explain quantum computing'.",
    example: "'python_web_scraping', 'explain_recursion', 'fix_login_bug'",
  },
  {
    term: "Topic Cluster",
    category: "Topics",
    definition: "A high-level grouping of similar topics, auto-generated by clustering similar intent labels together. Makes it easier to see broad patterns.",
    example: "'Software Development' cluster contains: python web scraping, javascript debugging, api integration, sql queries, etc.",
  },
  {
    term: "Conversation Turns",
    category: "Conversation",
    definition: "Number of back-and-forth exchanges in a conversation. 1 turn = user asks a question, AI gives a response.",
    subItems: [
      { label: "1–2 turns", description: "Simple question → direct answer" },
      { label: "3–6 turns", description: "Moderate back-and-forth, some follow-up needed" },
      { label: "7+ turns",  description: "Complex task, iterative problem-solving, or AI struggling" },
    ],
    example: "User: 'How do I reverse a list in Python?' AI: 'Use list.reverse()' → 1 turn",
  },
  {
    term: "Platform",
    category: "Conversation",
    definition: "Which AI service the conversation occurred on. Only shown when the dataset contains multiple platforms.",
    subItems: [
      { label: "ChatGPT",    description: "OpenAI's conversational AI" },
      { label: "Claude",     description: "Anthropic's AI assistant" },
      { label: "Gemini",     description: "Google's AI model" },
      { label: "Grok",       description: "xAI's conversational AI" },
      { label: "Perplexity", description: "AI-powered search engine" },
    ],
  },
  {
    term: "Completion Rate",
    category: "Performance",
    definition: "The percentage of conversations where the user successfully accomplished their goal (status = Completed).",
    formula: "Completion Rate = (completed conversations / total analyzed) × 100%",
    range: "0–100%. Higher is better.",
    example: "If 650 of 1,000 conversations end with status 'Completed', completion rate = 65%.",
  },
  {
    term: "Failure Rate",
    category: "Performance",
    definition: "The percentage of conversations that ended in failure or abandonment — the user did not get what they needed.",
    formula: "Failure Rate = (failed + abandoned) / total analyzed × 100%",
    range: "0–100%. Lower is better.",
    example: "A failure rate of 25% means 1 in 4 conversations didn't help the user.",
  },
  {
    term: "Abandonment Pattern",
    category: "Performance",
    definition: "At which turn number users most often stop responding without resolving their issue. Peaks in this histogram reveal where the AI consistently fails to satisfy users.",
    example: "If most abandonments happen at turn 3, users are giving the AI 3 chances before giving up.",
  },
  {
    term: "Emerging Topic",
    category: "Topics",
    definition: "A topic that first appeared in the dataset within the last 14 days. May indicate a new trend, a new product feature users are exploring, or a new user need.",
    example: "If 'claude_artifacts' first appeared 5 days ago and has 200 conversations, it's an emerging topic.",
  },
  {
    term: "Analysis Workers",
    category: "System",
    definition: "Background scripts that read conversations and apply AI analysis — assigning intent labels, quality scores, and completion statuses. Must be run to unlock most dashboard features.",
    example: "Run: python -m workers.intent_classifier && python -m workers.quality_scorer",
  },
];

const CATEGORIES = ["All", ...Array.from(new Set(TERMS.map((t) => t.category)))];

const QUALITY_COLORS: Record<string, string> = {
  "80–100": "#22c55e", "60–79": "#84cc16", "40–59": "#eab308", "20–39": "#f97316", "0–19": "#ef4444",
};
const PLATFORM_COLORS: Record<string, string> = {
  ChatGPT: "#10A37F", Claude: "#D97706", Gemini: "#4285F4", Grok: "#EF4444", Perplexity: "#8B5CF6",
};

// ─── Term Card ─────────────────────────────────────────────────────────────────

function TermCard({ term }: { term: GlossaryTerm }) {
  return (
    <div className="rounded-xl border border-white/[0.07] bg-[#13141b] p-5 space-y-3">
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <h3 className="text-base font-semibold text-white">{term.term}</h3>
        <span className="shrink-0 text-[10px] font-medium px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
          {term.category}
        </span>
      </div>

      {/* Definition */}
      <p className="text-sm text-zinc-400 leading-relaxed">{term.definition}</p>

      {/* Formula */}
      {term.formula && (
        <div className="bg-black/30 rounded-lg px-3 py-2 font-mono text-xs text-zinc-300 border border-white/[0.05]">
          {term.formula}
        </div>
      )}

      {/* Range */}
      {term.range && (
        <p className="text-xs text-zinc-500">
          <span className="text-zinc-400 font-medium">Range: </span>{term.range}
        </p>
      )}

      {/* Sub-items */}
      {term.subItems && term.subItems.length > 0 && (
        <div className="space-y-1.5">
          {term.subItems.map((item) => {
            const dotColor =
              QUALITY_COLORS[item.label] ??
              PLATFORM_COLORS[item.label] ??
              "#6b7280";
            return (
              <div key={item.label} className="flex items-start gap-3">
                <div className="flex items-center gap-2 shrink-0">
                  <span className="w-2 h-2 rounded-full shrink-0 mt-0.5" style={{ backgroundColor: dotColor }} />
                  <span className="text-xs font-medium text-zinc-300 w-24 shrink-0">{item.label}</span>
                </div>
                <span className="text-xs text-zinc-500 leading-relaxed">{item.description}</span>
              </div>
            );
          })}
        </div>
      )}

      {/* Example */}
      {term.example && (
        <div className="border-l-2 border-indigo-500/30 pl-3">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-zinc-600 mb-1">Example</p>
          <p className="text-xs text-zinc-500 italic">{term.example}</p>
        </div>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function Glossary() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");

  const filtered = TERMS.filter((t) => {
    const matchSearch =
      !search ||
      t.term.toLowerCase().includes(search.toLowerCase()) ||
      t.definition.toLowerCase().includes(search.toLowerCase());
    const matchCategory = activeCategory === "All" || t.category === activeCategory;
    return matchSearch && matchCategory;
  });

  return (
    <div className="p-8 max-w-5xl space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-white">Glossary</h1>
        <p className="text-sm text-zinc-500 mt-0.5">
          Reference for every metric and concept in Convometrics — {TERMS.length} definitions
        </p>
      </div>

      {/* Search + category filter */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 max-w-xs">
          <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            type="text"
            placeholder="Search definitions..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-[#13141b] border border-white/[0.08] rounded-lg pl-9 pr-3 py-2 text-sm text-zinc-300 focus:outline-none focus:border-white/20 placeholder:text-zinc-600"
          />
        </div>
        <div className="flex flex-wrap gap-1.5">
          {CATEGORIES.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
                activeCategory === cat
                  ? "bg-indigo-500/20 text-indigo-300 border border-indigo-500/30"
                  : "text-zinc-500 hover:text-zinc-300 hover:bg-white/[0.04] border border-transparent"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Results count */}
      {(search || activeCategory !== "All") && (
        <p className="text-xs text-zinc-600">
          {filtered.length} {filtered.length === 1 ? "term" : "terms"} found
          {search && ` matching "${search}"`}
        </p>
      )}

      {/* Term cards grid */}
      {filtered.length === 0 ? (
        <div className="text-center py-16 text-zinc-600">
          <svg className="w-10 h-10 mx-auto mb-3 opacity-40" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <p className="text-sm">No terms found for &ldquo;{search}&rdquo;</p>
          <button onClick={() => { setSearch(""); setActiveCategory("All"); }}
            className="mt-2 text-xs text-indigo-400 hover:text-indigo-300">
            Clear search
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
          {filtered.map((term) => (
            <TermCard key={term.term} term={term} />
          ))}
        </div>
      )}
    </div>
  );
}
